### ISSUE TITLE
ERROR:asyncio:SSL error in data received

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Pushl#26]
This happens when running pushl against an SSL-served RSS/Atom feed or entries. It seems to be an upstream bug in aiohttp, but it could be a problem with connection pooling on the Pushl end.

Output log gets spammed with:

```
ERROR:asyncio:SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xf45838ac>
transport: <_SelectorSocketTransport fd=47 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
```

**Comment by fluffy-critter** [comment]
This turns out to be a bug in the Python 3.7.4 distribution on Linux, and will be fixed there.

https://github.com/aio-libs/aiohttp/issues/3535
