### ISSUE TITLE
AttributeError in webmention handler

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Pushl#29]
```
remote: ERROR:asyncio:Task exception was never retrieved
remote: future: <Task finished coro=<Pushl.send_webmention() done, defined at /home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/pushl/__init__.py:162> exception=AttributeError("'Target' object has no attribute 'href'")>
remote: Traceback (most recent call last):
remote:   File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/pushl/__init__.py", line 178, in send_webmention
remote:     await target.send(self, entry)
remote:   File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/pushl/webmentions.py", line 159, in send
remote:     LOGGER.debug("%s -> %s via %s %s", entry.url, self.href,
remote: AttributeError: 'Target' object has no attribute 'href'
```

I *think* this was already fixed by 4836b49445dd7ff7fd3ec9f1270be9281d2b1064 but it's worth double-checking.

**Comment by fluffy-critter** [comment]
It still persists in the latest release, and makes no heckin' sense.
