### ISSUE TITLE
TypeError: shield() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by liskin** [PlaidWeb/Pushl#47]
With Python 3.10, I'm getting

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-174' coro=<Pushl.send_webmention() done, defined at /home/tomi/.local/pipx/venvs/pushl/lib/python3.10/site-packages/pushl/__init__.py:180> exception=TypeError("shield() got an unexpected keyword argument 'loop'")>
Traceback (most recent call last):
  File "/home/tomi/.local/pipx/venvs/pushl/lib/python3.10/site-packages/pushl/__init__.py", line 190, in send_webmention
    target, code, cached = await webmentions.get_target(self, dest)
  File "/home/tomi/.local/pipx/venvs/pushl/lib/python3.10/site-packages/async_lru.py", line 212, in wrapped
    return (yield from asyncio.shield(fut, loop=_loop))
TypeError: shield() got an unexpected keyword argument 'loop'
```

**Comment by fluffy-critter** [comment]
Huh, interesting. I'll have to check my Pushl logs, since I've been running on 3.10 but haven't been paying attention to that.

It looks like the problem is in [async-lru](https://github.com/aio-libs/async-lru) although there doesn't seem to be an open issue for it yet.

**Comment by fluffy-critter** [comment]
Oh, what version of async-lru is running in your environment? Is it possible that it needs to be updated?

**Comment by liskin** [comment]
Oh, indeed it looks like there isn't that line any more after reinstalling into a fresh venv. Should've taken a closer look at the trace. Sorry for the noise!

**Comment by fluffy-critter** [comment]
No problem! This got me to do an overdue version bump with new versions anyway.
